try do
  throw(:error)
catch
end
